[versions]

kotlin = "1.8.10"
kover = "0.6.1"

[libraries]
# COMMON
common-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
common-testAnnotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }

# CLASSPATHS
classpaths-kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
classpaths-kover = { module = "org.jetbrains.kotlinx:kover", version.ref = "kover" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
